plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.1
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
  CountComments: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false  

Rails:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/system/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 3

RSpec/ContextWording:
  Enabled: false  

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 20  

Lint/EmptyBlock:
  Enabled: false

SuggestExtensions:
  Enabled: false