version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"

  sidekiq:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    command: bundle exec sidekiq -C config/sidekiq.yml

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dissent_cart_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7.0.15-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  redis-gui:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"

volumes:
  postgres_data:
  redis_data:
  gem_cache: