default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: <%= Rails.application.credentials.dig(:development, :database_username) %>

development:
  <<: *default
  database: dissent_cart_development
  password: <%= Rails.application.credentials.dig(:development, :database_password) %>

test:
  <<: *default
  database: dissent_cart_test

production:
  <<: *default
  database: dissent_cart_production
  password: <%= Rails.application.credentials.dig(:production, :database_password) %>