default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%=  ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DATABASE_USERNAME') { Rails.application.credentials.dig(:development, :database_username) } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { Rails.application.credentials.dig(:development, :database_password) } %>

development:
  <<: *default
  database: dissent_cart_development

test:
  <<: *default
  database: dissent_cart_test
