:queues:
  - default
  - mailers

:schedule:
  abandon_carts_job:
    cron: "0 */3 * * *"
    class: AbandonCartsJob
    queue: default
    description: "Marca carrinhos abandonados"
    
  delete_abandoned_carts_job:
    cron: "0 0 * * *"
    class: DeleteAbandonedCartsJob
    queue: default
    description: "Remove carrinhos abandonados hรก mais de 7 dias"

:concurrency: 5
:redis_url: <%= ENV.fetch('REDIS_URL', 'redis://redis:6379/0') %>